import re

# Cybersecurity keywords for basic filtering
CYBER_KEYWORDS = [
    "security", "cyber", "hack", "malware", "ransomware", "siem", "soc", "network",
    "firewall", "encryption", "cryptography", "owasp", "vulnerability", "exploit",
    "forensics", "active directory", "linux", "windows", "cloud", "aws", "azure",
    "phishing", "ids", "ips", "wireshark", "nmap", "burp", "splunk", "wazuh",
    "yara", "mitre", "nist", "iso 27001", "threat", "reverse engineering", "hashing",
    "penetration", "pentest", "ctf", "capture the flag", "sql injection", "xss",
    "buffer overflow", "zero day", "apt", "ddos", "botnet", "rootkit", "trojan",
    "spyware", "adware", "keylogger", "social engineering", "osint", "digital forensics",
    "incident response", "risk assessment", "compliance", "gdpr", "hipaa",
    "blockchain", "smart contract", "iot security", "mobile security", "web security",
    "api security", "devsecops", "secure coding", "code review", "audit", "log analysis",
    "packet analysis", "protocol", "tcp/ip", "dns", "dhcp", "vpn", "proxy",
    "certificate", "ssl", "tls", "pki", "authentication", "authorization", "oauth",
    "jwt", "session", "cookie", "csrf", "cors", "csp", "waf", "honeypot", "sandbox",
    "virtualization", "container", "docker", "kubernetes", "ansible", "terraform",
    "cloudflare", "fortinet", "palo alto", "cisco", "juniper", "checkpoint",
    "kaspersky", "mcafee", "symantec", "crowdstrike", "sentinelone", "carbon black",
    "darktrace", "elastic", "grafana", "prometheus", "python", "bash", "powershell",
    "automation", "orchestration", "vmware", "aws", "azure", "gcp", "ec2", "s3",
    "lambda", "rds", "dynamodb", "cloudfront", "route53", "azure ad", "intune",
    "defender", "sentinel", "gke", "aks", "eks", "firebase", "mongodb", "postgresql",
    "mysql", "redis", "elasticsearch", "kafka", "rabbitmq", "grpc", "graphql",
    "rest", "websocket", "microservices", "serverless", "zero trust", "sase",
    "sd-wan", "dlp", "data loss prevention", "data privacy", "data protection",
    "identity", "access management", "iam", "mfa", "2fa", "biometric", "ueba",
    "soar", "edr", "xdr", "mdr", "ndr", "threat intelligence", "threat hunting",
    "threat modeling", "attack surface", "vulnerability management", "patch management",
    "asset management", "cmdb", "itsm", "itil", "cobit", "togaf", "gartner",
    "cyber kill chain", "mitre att&ck", "diamond model", "pyramid of pain",
    "ioc", "ttp", "nation state", "hacktivist", "insider threat", "supply chain",
    "third party risk", "penetration test", "red team", "blue team", "purple team",
    "bug bounty", "responsible disclosure", "cve", "cvss", "cwe", "capec",
    "stix", "taxi", "openioc", "snort", "suricata", "zeek", "pfsense", "opnsense",
    "nftables", "iptables", "fail2ban", "crowdsec", "ossec", "osquery", "velociraptor",
    "thehive", "cortex", "misp", "opencti", "shodan", "censys", "haveibeenpwned",
    "recorded future", "mandiant", "fireeye", "cybereason", "vectra", "extrahop",
    "corelight", "gigamon", "netscout", "radware", "imperva", "f5", "akamai",
    "fastly", "stackpath", "sucuri", "wordfence", "malcare", "bulletproof",
    "secupress", "all in one wp security", "wp fail2ban",
]

# Patterns that indicate prompt injection attempts
BLOCKED_PATTERNS = [
    r"ignore\s+(all\s+)?(previous|prior|earlier)\s+(instructions?|prompts?|commands?|directives?)",
    r"disregard\s+(all\s+)?(previous|prior|earlier)\s+(instructions?|prompts?|commands?|directives?)",
    r"forget\s+(all\s+)?(previous|prior|earlier)\s+(instructions?|prompts?|commands?|directives?)",
    r"override\s+(all\s+)?(previous|prior|earlier)\s+(instructions?|prompts?|commands?|directives?)",
    r"bypass\s+(all\s+)?(previous|prior|earlier)\s+(instructions?|prompts?|commands?|directives?)",
    r"you\s+are\s+now\s+(a\s+)?(hacker|attacker|criminal|malicious|evil|bad)",
    r"act\s+as\s+(a\s+)?(hacker|attacker|criminal|malicious|evil|bad)",
    r"pretend\s+to\s+be\s+(a\s+)?(hacker|attacker|criminal|malicious|evil|bad)",
    r"roleplay\s+as\s+(a\s+)?(hacker|attacker|criminal|malicious|evil|bad)",
    r"simulate\s+(a\s+)?(hacker|attacker|criminal|malicious|evil|bad)",
    r"write\s+.*exploit\s+.*step\s+by\s+step",
    r"how\s+to\s+hack\s+.*specific",
    r"how\s+to\s+attack\s+.*specific",
    r"how\s+to\s+break\s+into\s+.*specific",
    r"how\s+to\s+compromise\s+.*specific",
    r"how\s+to\s+exploit\s+.*specific",
    r"give\s+me\s+.*code\s+.*attack",
    r"give\s+me\s+.*script\s+.*hack",
    r"generate\s+.*malware",
    r"generate\s+.*virus",
    r"generate\s+.*trojan",
    r"generate\s+.*ransomware",
    r"generate\s+.*keylogger",
    r"generate\s+.*botnet",
    r"generate\s+.*exploit",
    r"create\s+.*malware",
    r"create\s+.*virus",
    r"create\s+.*trojan",
    r"create\s+.*ransomware",
    r"create\s+.*keylogger",
    r"create\s+.*botnet",
    r"create\s+.*exploit",
    r"build\s+.*malware",
    r"build\s+.*virus",
    r"build\s+.*trojan",
    r"build\s+.*ransomware",
    r"build\s+.*keylogger",
    r"build\s+.*botnet",
    r"build\s+.*exploit",
    r"develop\s+.*malware",
    r"develop\s+.*virus",
    r"develop\s+.*trojan",
    r"develop\s+.*ransomware",
    r"develop\s+.*keylogger",
    r"develop\s+.*botnet",
    r"develop\s+.*exploit",
    r"bypass\s+.*filter",
    r"bypass\s+.*restriction",
    r"bypass\s+.*limitation",
    r"bypass\s+.*security",
    r"bypass\s+.*protection",
    r"jailbreak",
    r"prompt\s+injection",
    r"system\s+prompt\s+leak",
    r"reveal\s+your\s+instructions",
    r"show\s+me\s+your\s+system\s+prompt",
    r"what\s+are\s+your\s+instructions",
    r"what\s+is\s+your\s+system\s+prompt",
    r"DAN",
    r"Developer\s+Mode",
    r"STAN",
    r"DUDE",
    r"AIM",
    r"UCAR",
    r"Oppo",
    r"Mongo\s+Tom",
    r"evil\s+confidant",
    r"translator\s+bot",
    r"hypothetical\s+response",
    r"hypothetically",
    r"in\s+a\s+hypothetical\s+scenario",
    r"for\s+educational\s+purposes\s+only",
    r"for\s+research\s+purposes\s+only",
    r"white\s+hat\s+only",
    r"ethical\s+hacking\s+only",
    r"penetration\s+testing\s+only",
    r"CTF\s+only",
    r"capture\s+the\s+flag\s+only",
]

def is_cyber_related(message: str) -> bool:
    """Check if message is cybersecurity related using keyword matching."""
    message_lower = message.lower()
    for keyword in CYBER_KEYWORDS:
        if keyword in message_lower:
            return True
    return False

def is_malicious_prompt(message: str) -> bool:
    """Detect prompt injection and malicious request attempts."""
    message_lower = message.lower()
    for pattern in BLOCKED_PATTERNS:
        if re.search(pattern, message_lower):
            return True
    return False
